# Generated by Django 2.2.7 on 2019-11-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.IntegerField(blank=True, max_length=9, null=True, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, max_length=2, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Department')),
            ],
        ),
    ]
